export const texts = {
  vi: {
    trendingSongs: "Những bài hát thịnh hành 🎵",
    popularArtists: "Nghệ sĩ phổ biến ✨",
    playlistsForYou: "Playlist gợi ý cho bạn 🎶",
    yourLibrary: "Thư viện của bạn 🎧",
    favorites: "Yêu thích 💖",
    notPlayed: "Bạn chưa nghe bài nào.",
    chooseLanguage: "Chọn một ngôn ngữ",
    languageNote: "Lựa chọn này sẽ cập nhật nội dung bạn đọc trên Spotify Clone.",

    premiumTitle: "Nghe nhạc không giới hạn.",
    premiumSubtitle: "Dùng thử Premium Individual trong 2 tháng, chỉ 59.000 ₫.",
    premiumTrialButton: "Dùng thử 2 tháng với giá 59.000 ₫",
    premiumViewPlans: "Xem tất cả các gói",
    premiumNote: "59.000 ₫ cho 2 tháng, sau đó là 59.000 ₫/tháng. Chỉ áp dụng ưu đãi nếu bạn chưa từng dùng gói Premium.",
    premiumTerms: "Có áp dụng điều khoản",
    supportTitle: "Chúng tôi có thể giúp gì cho bạn?",
  supportSubtitle: "Đăng nhập để được trợ giúp nhanh hơn",
  supportPlaceholder: "Tìm kiếm",
  supportSections: [
    "Thanh toán và hóa đơn",
    "Quản lý tài khoản của bạn",
    "Các gói Premium",
    "Tính năng trong ứng dụng",
    "Thiết bị và khắc phục sự cố",
    "An toàn và quyền riêng tư"
  ],
  supportQuickHelp: "Trợ giúp nhanh",
  supportQuickList: [
    "Không thể đăng nhập vào Spotify",
    "Trợ giúp về khoản thanh toán không thành công",
    "Bị tính phí quá nhiều",
    "Cách thay đổi thông tin thanh toán"
  ],
  downloadTitle: "Tải xuống TieM",
  downloadSubtitle: "Phát hàng triệu bài hát và podcast trên thiết bị của bạn.",
  downloadLink: "Tải xuống trực tiếp từ TieM",
  downloadDeviceTitle: "Nghe trên cả điện thoại di động và máy tính bảng",
  downloadDeviceDesc: "Sử dụng TieM trên điện thoại hoặc máy tính bảng một cách miễn phí, dễ dàng và vui vẻ.",
  signupTitle: "Đăng ký để bắt đầu nghe",
  emailLabel: "Địa chỉ email",
  emailPlaceholder: "name@domain.com",
  usePhone: "Dùng số điện thoại.",
  next: "Tiếp theo",
  or: "hoặc",
  signupGoogle: "Đăng ký bằng Google",
  signupApple: "Đăng ký bằng Apple",
  alreadyHaveAccount: "Bạn đã có tài khoản?",
  loginHere: "Đăng nhập tại đây.",
  privacyLine: "Trang này được bảo vệ bởi reCAPTCHA và tuân theo",
  privacyPolicy: "Chính sách quyền riêng tư",
  terms: "Điều khoản dịch vụ",
  byGoogle: "của Google.",

  loginTitle: "Đăng nhập vào Spotify",
  loginGoogle: "Tiếp tục bằng Google",
  loginApple: "Tiếp tục bằng Apple",
  loginPhone: "Tiếp tục bằng số điện thoại",
  emailOrUsername: "Email hoặc tên người dùng",
  noAccount: "Bạn chưa có tài khoản?",
  signupSpotify: "Đăng ký Spotify",
   footerSections: [
    {
      title: "Công ty",
      items: ["Giới thiệu", "Việc làm", "For the Record"]
    },
    {
      title: "Cộng đồng",
      items: ["Dành cho các Nghệ sĩ", "Nhà phát triển", "Quảng cáo", "Nhà đầu tư", "Nhà cung cấp"]
    },
    {
      title: "Liên kết hữu ích",
      items: ["Hỗ trợ", "Ứng dụng Di động Miễn phí", "Phổ biến theo quốc gia"]
    },
    {
      title: "Các gói của TieM",
      items: ["Premium Individual", "Premium Student", "TieM Free"]
    }
  ],
  podcastTitle: "Podcast",
  podcastCategories: "Danh mục",
  searchResultTitle: "Kết quả tìm kiếm cho",
  searchNotFound: "Không tìm thấy kết quả nào phù hợp.",
  searchPlaceholder: "Bạn muốn phát nội dung gì?",
  noSearchResult: "Không tìm thấy kết quả",
  premium: "Premium",
  support: "Hỗ trợ",
  download: "Tải xuống",
  installApp: "Cài đặt Ứng dụng",
  signup: "Đăng ký",
  login: "Đăng nhập",
  promoTitle: "Nghe không giới hạn. Dùng thử gói Premium trong 3 tháng với giá 59.000 ₫.",
    promoDesc: "Chỉ áp dụng cho người dùng mới. Sau đó là 59.000 ₫/tháng. Có áp dụng điều khoản. Ưu đãi kết thúc vào 15 tháng 7, 2025.",
    promoBtn: "Dùng thử 3 tháng với giá 59.000 ₫",
    searchPlaceholder: "Tìm kiếm tài khoản hoặc bài viết trợ giúp",
    yourPlan: "Gói của bạn",
    account: "Tài khoản",
    managePlan: "Quản lý gói đăng ký",
    editProfile: "Chỉnh sửa thông tin cá nhân",
    recoverPlaylist: "Khôi phục danh sách phát",
    noResult: "Không tìm thấy kết quả nào.",

    planFeatures: [
      "1 tài khoản Free",
      "Nghe nhạc có quảng cáo",
      "Chỉ nghe trực tuyến",
      "Phát nhạc ngẫu nhiên",
      "Chất lượng âm thanh cơ bản",
    ],
    free: "Miễn phí",
    tryPremium: "Dùng Premium",
    backToProfile: "Quay lại trang hồ sơ",

    noDeleted: "Không còn bài hát nào cần khôi phục.",
    restore: "Khôi phục",

    usernameLabel: "Tên người dùng",
    email: "Email",
    gender: "Giới tính",
    birthdate: "Ngày sinh",
    country: "Quốc gia hoặc khu vực",
    shareData: "Chia sẻ dữ liệu đăng ký với các nhà cung cấp nội dung Spotify cho mục đích tiếp thị.",
    cancel: "Hủy",
    saveProfile: "Lưu hồ sơ",
  
  
},
    


  en: {
    trendingSongs: "Trending Songs 🎵",
    popularArtists: "Popular Artists ✨",
    playlistsForYou: "Playlists For You 🎶",
    yourLibrary: "Your Library 🎧",
    favorites: "Favorites 💖",
    notPlayed: "You haven't played anything yet.",
    chooseLanguage: "Choose a Language",
    languageNote: "This selection will update your display language on Spotify Clone.",

    premiumTitle: "Unlimited music streaming.",
    premiumSubtitle: "Try Premium Individual for 2 months at only 59,000 ₫.",
    premiumTrialButton: "Try 2 months for 59,000 ₫",
    premiumViewPlans: "See all plans",
    premiumNote: "59,000 ₫ for 2 months, then 59,000 ₫/month. Offer only applies if you haven't used Premium before.",
    premiumTerms: "Terms apply",
    supportTitle: "How can we help you?",
  supportSubtitle: "Log in to get faster support",
  supportPlaceholder: "Search",
  supportSections: [
    "Payments and Billing",
    "Manage Your Account",
    "Premium Plans",
    "App Features",
    "Devices and Troubleshooting",
    "Safety and Privacy"
  ],
  supportQuickHelp: "Quick Help",
  supportQuickList: [
    "Can't log in to Spotify",
    "Help with a failed payment",
    "Overcharged",
    "How to change payment information"
  ],
  downloadTitle: "Download TieM",
  downloadSubtitle: "Stream millions of songs and podcasts on your device.",
  downloadLink: "Download directly from TieM",
  downloadDeviceTitle: "Listen on mobile and tablet",
  downloadDeviceDesc: "Use TieM for free on your phone or tablet – it's easy and fun!",
  signupTitle: "Sign up to start listening",
  emailLabel: "Email address",
  emailPlaceholder: "name@domain.com",
  usePhone: "Use phone number.",
  next: "Next",
  or: "or",
  signupGoogle: "Sign up with Google",
  signupApple: "Sign up with Apple",
  alreadyHaveAccount: "Already have an account?",
  loginHere: "Log in here.",
  privacyLine: "This page is protected by reCAPTCHA and subject to",
  privacyPolicy: "Privacy Policy",
  terms: "Terms of Service",
  byGoogle: "by Google.",

  loginTitle: "Log in to Spotify",
  loginGoogle: "Continue with Google",
  loginApple: "Continue with Apple",
  loginPhone: "Continue with phone number",
  emailOrUsername: "Email or username",
  noAccount: "Don't have an account?",
  signupSpotify: "Sign up for Spotify",
  footerSections: [
    {
      title: "Company",
      items: ["About", "Jobs", "For the Record"]
    },
    {
      title: "Community",
      items: ["For Artists", "Developers", "Advertising", "Investors", "Vendors"]
    },
    {
      title: "Useful Links",
      items: ["Support", "Free Mobile App", "Popular by Country"]
    },
    {
      title: "Plans",
      items: ["Premium Individual", "Premium Student", "TieM Free"]
    }
  ],
  podcastTitle: "Podcasts",
  podcastCategories: "Categories",
  searchResultTitle: "Search results for",
  searchNotFound: "No matching results found.",
   searchPlaceholder: "What do you want to play?",
  noSearchResult: "No results found",
  premium: "Premium",
  support: "Support",
  download: "Download",
  installApp: "Install App",
  signup: "Sign Up",
  login: "Log In",
  promoTitle: "Listen without limits. Try Premium for 3 months at 59,000 ₫.",
    promoDesc: "Only for new users. Then 59,000 ₫/month. Terms apply. Offer ends July 15, 2025.",
    promoBtn: "Try 3 months for 59,000 ₫",
    searchPlaceholder: "Search for account or help articles",
    yourPlan: "Your Plan",
    account: "Account",
    managePlan: "Manage Subscription",
    editProfile: "Edit Profile",
    recoverPlaylist: "Recover Playlist",
    noResult: "No result found.",

    planFeatures: [
      "1 Free account",
      "Music with ads",
      "Online listening only",
      "Shuffle play",
      "Basic audio quality",
    ],
    free: "Free",
    tryPremium: "Try Premium",
    backToProfile: "Back to Profile",

    noDeleted: "No deleted songs to recover.",
    restore: "Restore",

    usernameLabel: "Username",
    email: "Email",
    gender: "Gender",
    birthdate: "Date of birth",
    country: "Country or region",
    shareData: "Share registration data with Spotify's content providers for marketing.",
    cancel: "Cancel",
    saveProfile: "Save Profile",
},
  

  ja: {
    trendingSongs: "人気の曲 🎵",
    popularArtists: "人気アーティスト ✨",
    playlistsForYou: "おすすめプレイリスト 🎶",
    yourLibrary: "あなたのライブラリ 🎧",
    favorites: "お気に入り 💖",
    notPlayed: "再生履歴がありません。",
    chooseLanguage: "言語を選択してください",
    languageNote: "この選択により表示言語が更新されます",

    premiumTitle: "無制限で音楽を楽しもう。",
    premiumSubtitle: "Premium Individualを2ヶ月間たったの59,000 ₫でお試し。",
    premiumTrialButton: "59,000 ₫で2ヶ月試す",
    premiumViewPlans: "すべてのプランを見る",
    premiumNote: "2ヶ月で59,000 ₫、その後は月額59,000 ₫。初めての方限定。",
    premiumTerms: "利用規約が適用されます",
    supportTitle: "どのようなご用件でしょうか？",
  supportSubtitle: "ログインすると、サポートが早くなります",
  supportPlaceholder: "検索",
  supportSections: [
    "支払いと請求",
    "アカウントの管理",
    "プレミアムプラン",
    "アプリの機能",
    "デバイスとトラブルシューティング",
    "安全とプライバシー"
  ],
  supportQuickHelp: "クイックサポート",
  supportQuickList: [
    "Spotifyにログインできない",
    "支払いエラーに関するサポート",
    "二重請求された",
    "支払い情報を変更する方法"
  ],
  downloadTitle: "TieM をダウンロード",
  downloadSubtitle: "数百万曲とポッドキャストをあなたのデバイスで再生しよう。",
  downloadLink: "TieM から直接ダウンロード",
  downloadDeviceTitle: "スマホやタブレットでも聴ける",
  downloadDeviceDesc: "TieM はスマホやタブレットでも無料で簡単に使えて楽しい！",
  signupTitle: "登録して音楽を聴き始めよう",
  emailLabel: "メールアドレス",
  emailPlaceholder: "name@domain.com",
  usePhone: "電話番号を使う",
  next: "次へ",
  or: "または",
  signupGoogle: "Googleで登録",
  signupApple: "Appleで登録",
  alreadyHaveAccount: "すでにアカウントをお持ちですか？",
  loginHere: "こちらからログイン",

  privacyLine: "このページはreCAPTCHAによって保護されており、",
  privacyPolicy: "プライバシーポリシー",
  terms: "利用規約",
  byGoogle: "が適用されます。",

  loginTitle: "Spotifyにログイン",
  loginGoogle: "Googleで続行",
  loginApple: "Appleで続行",
  loginPhone: "電話番号で続行",
  emailOrUsername: "メールアドレスまたはユーザー名",
  noAccount: "アカウントをお持ちでないですか？",
  signupSpotify: "Spotifyに登録",
  footerSections: [
    {
      title: "会社情報",
      items: ["会社概要", "採用情報", "公式情報"]
    },
    {
      title: "コミュニティ",
      items: ["アーティスト向け", "開発者", "広告", "投資家", "ベンダー"]
    },
    {
      title: "便利なリンク",
      items: ["サポート", "無料モバイルアプリ", "国別人気"]
    },
    {
      title: "TieMのプラン",
      items: ["プレミアム個人", "プレミアム学生", "TieM無料"]
    }
  ],
  podcastTitle: "ポッドキャスト",
  podcastCategories: "カテゴリ",
  searchResultTitle: "検索結果：",
  searchNotFound: "該当する結果が見つかりませんでした。",
  searchPlaceholder: "再生したいものは？",
  noSearchResult: "結果が見つかりません",
  premium: "プレミアム",
  support: "サポート",
  download: "ダウンロード",
  installApp: "アプリをインストール",
  signup: "登録",
  login: "ログイン",
  promoTitle: "無制限で聴こう。3か月間プレミアムを59,000 ₫でお試し。",
    promoDesc: "新規ユーザーのみ対象。その後は月額59,000 ₫。利用規約が適用されます。2025年7月15日まで有効。",
    promoBtn: "3か月間を59,000 ₫で試す",
    searchPlaceholder: "アカウントまたはヘルプ記事を検索",
    yourPlan: "あなたのプラン",
    account: "アカウント",
    managePlan: "サブスクリプション管理",
    editProfile: "プロフィール編集",
    recoverPlaylist: "プレイリストを復元",
    noResult: "結果が見つかりません。",

    planFeatures: [
      "無料アカウント1つ",
      "広告付き音楽",
      "オンライン再生のみ",
      "シャッフル再生",
      "標準音質",
    ],
    free: "無料",
    tryPremium: "Premiumを試す",
    backToProfile: "プロフィールに戻る",

    noDeleted: "復元可能な曲がありません。",
    restore: "復元",

    usernameLabel: "ユーザー名",
    email: "メールアドレス",
    gender: "性別",
    birthdate: "生年月日",
    country: "国または地域",
    shareData: "Spotifyのコンテンツプロバイダーと登録データを共有してマーケティング目的に使用する。",
    cancel: "キャンセル",
    saveProfile: "プロフィールを保存",

  }
};
